sudo: false
language: go
go:
  - 1.9.x
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race
matrix:
  allow_failures:
    - go: master
  fast_finish: true
notifications:
  email: false
env:
  -GOGIVENS_OUTPUT_DIR=/tmp
before_deploy:
  - test $TRAVIS_TEST_RESULT = 0\
    && cp /tmp/*.html ./docs
deploy:
  local-dir: /docs
  file_glob: true
    file: *.html
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  verbose: true
  on:
    branch: master
